[package]
name = "rspc"
description = "A framework for building typesafe web backends in Rust"
version = "0.3.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://rspc.dev"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

[features]
default = []

[dependencies]
# Public
serde = "1"
futures = "0.3"
specta = { version = "=2.0.0-rc.20", features = ["derive"] } # TODO: Drop requirement on `derive`
specta-util = "0.0.7"

# Private
serde-value = "0.7"
erased-serde = "0.4"

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
